In [1]:
import pandas as pd
import numpy as np

In [4]:
admissionDrug=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\admissionDrug.csv")
admissionDrug

,admissiondrugid,patientunitstayid,drugoffset,drugenteredoffset,drugnotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,drugdosage,drugunit,drugadmitfrequency,drughiclseqno
0,1589228,242954,64,79,Admission,eCM Primary,THC Nurse,True,True,ELIQUIS ...,0.0,,,37792
1,2063596,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,VICTOZA 2-PAK ...,0.0,,,36436
2,2063595,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,POTASSIUM CHLORIDE ...,0.0,,,549
3,2063590,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,CITALOPRAM HBR ...,0.0,,,10321
4,2063594,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,OMEPRAZOLE ...,0.0,,,4673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874915,19152155,3353117,46,99,Follow-up Consultation/Other,critical care medicine (CCM),Attending Physician,False,False,ASPIRIN ...,0.0,,,1820
874916,19152154,3353117,46,99,Follow-up Consultation/Other,critical care medicine (CCM),Attending Physician,False,False,ATENOLOL ...,0.0,,,2104
874917,19152153,3353117,46,99,Follow-up Consultation/Other,critical care medicine (CCM),Attending Physician,False,False,SIMVASTATIN ...,0.0,,,6312
874918,19152157,3353117,46,99,Follow-up Consultation/Other,critical care medicine (CCM),Attending Physician,False,False,FENOFIBRATE ...,0.0,,,20377
874919,19152156,3353117,46,99,Follow-up Consultation/Other,critical care medicine (CCM),Attending Physician,False,False,LISINOPRIL ...,0.0,,,132

In [6]:
admissionDx=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\admissionDx.csv")
admissionDx

,admissiondxid,patientunitstayid,admitdxenteredoffset,admitdxpath,admitdxname,admitdxtext
0,8023778,2900217,62,admission diagnosis|Operative Organ Systems|Or...,Cardiovascular,Cardiovascular
1,8023777,2900217,62,admission diagnosis|Was the patient admitted f...,Yes,Yes
2,8023779,2900217,62,admission diagnosis|All Diagnosis|Operative|Di...,Aortic and Mitral valve replacement,Aortic and Mitral valve replacement
3,7929318,2900240,53,admission diagnosis|Non-operative Organ System...,Gastrointestinal,Gastrointestinal
4,7929317,2900240,53,admission diagnosis|Was the patient admitted f...,No,No
...,...,...,...,...,...,...
626853,7902610,2900186,55,admission diagnosis|Non-operative Organ System...,Cardiovascular,Cardiovascular
626854,8041507,2900196,48,admission diagnosis|Non-operative Organ System...,Metabolic/Endocrine,Metabolic/Endocrine
626855,8041506,2900196,48,admission diagnosis|Was the patient admitted f...,No,No
626856,8041508,2900196,48,admission diagnosis|All Diagnosis|Non-operativ...,Hypoglycemia,Hypoglycemia
626857,8023776,2900217,62,admission diagnosis|Elective|Yes,Yes,Yes

In [8]:
allergy=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\allergy.csv")
allergy

,allergyid,patientunitstayid,allergyoffset,allergyenteredoffset,allergynotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,allergytype,allergyname,drughiclseqno
0,378178,242070,3,3,Daily Progress,eCM Primary,Other,False,True,NaN,Non Drug,Red Dye ...,NaN
1,298537,242070,23,63,Admission,eCM Primary,THC Nurse,False,True,NaN,Non Drug,Red Dye ...,NaN
2,378177,242070,3,3,Daily Progress,eCM Primary,Other,False,True,NaN,Non Drug,Tape ...,NaN
3,298536,242070,23,63,Admission,eCM Primary,THC Nurse,False,True,NaN,Non Drug,Tape ...,NaN
4,385834,242083,1316,1319,Comprehensive Progress,eCM Primary,THC Nurse,False,True,NaN,Non Drug,Lisinopril ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
251944,4240630,3353213,22,57,Admission,eCM Primary,THC Nurse,True,True,TRAMADOL HCL ...,Drug,TRAMADOL HCL ...,8317.0
251945,4240444,3353213,2199,2201,Comprehensive Progress,eCM Primary,THC Nurse,True,True,TRAMADOL HCL ...,Drug,TRAMADOL HCL ...,8317.0
251946,4237873,3353213,22,57,Admission,eCM Primary,THC Nurse,True,True,PROCHLORPERAZINE EDISYLATE ...,Drug,PROCHLORPERAZINE EDISYLATE ...,1628.0
251947,4200126,3353254,31,41,Admission,eCM Primary,THC Nurse,True,True,VANCOMYCIN ...,Drug,VANCOMYCIN ...,37442.0
251948,4221244,3353254,31,41,Admission,eCM Primary,THC Nurse,True,True,KEFLEX ...,Drug,KEFLEX ...,13908.0

In [2]:
apacheApsVar=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\apacheApsVar.csv")
apacheApsVar

,apacheapsvarid,patientunitstayid,intubated,vent,dialysis,eyes,motor,verbal,meds,urine,...,ph,hematocrit,creatinine,albumin,pao2,pco2,bun,glucose,bilirubin,fio2
0,2,141168,0,0,0,4,6,5,0,-1.0000,...,-1.000,40.1,2.30,3.1,-1.0,-1.0,27.0,95.0,4.1,-1.0
1,2399659,141178,0,0,0,-1,-1,-1,-1,-1.0000,...,-1.000,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,167885,141194,0,0,0,3,6,4,0,-1.0000,...,-1.000,27.4,2.51,2.3,-1.0,-1.0,31.0,168.0,0.4,-1.0
3,70691,141197,0,0,0,4,6,5,0,-1.0000,...,-1.000,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,2279689,141203,0,1,0,1,3,1,0,-1.0000,...,7.450,36.9,0.56,-1.0,51.0,37.0,9.0,145.0,-1.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171172,1325400,3353235,0,0,0,4,6,5,0,1751.1552,...,-1.000,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
171173,1528627,3353237,0,0,0,4,6,4,0,5724.7776,...,-1.000,39.0,1.07,3.5,-1.0,-1.0,32.0,139.0,0.7,-1.0
171174,1546299,3353251,1,1,0,1,1,1,0,358.9920,...,7.224,-1.0,2.43,-1.0,80.0,44.0,30.0,346.0,-1.0,100.0
171175,2085296,3353254,0,0,0,4,6,5,0,2171.6640,...,-1.000,32.0,-1.00,-1.0,-1.0,-1.0,-1.0,137.0,-1.0,-1.0
171176,1404922,3353263,0,0,0,4,6,5,0,-1.0000,...,-1.000,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [19]:
apacheApsVar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171177 entries, 0 to 171176
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   apacheapsvarid     171177 non-null  int64
 1   patientunitstayid  171177 non-null  int64
 2   intubated          171177 non-null  int64
 3   vent               171177 non-null  int64
 4   dialysis           171177 non-null  int64
 5   eyes               171177 non-null  int64
 6   motor              171177 non-null  int64
 7   verbal             171177 non-null  int64
 8   meds               171177 non-null  int64
 9   urine              171177 non-null  float64
 10  wbc                171177 non-null  float64
 11  temperature        171177 non-null  float64
 12  respiratoryrate    171177 non-null  float64
 13  sodium             171177 non-null  float64
 14  heartrate          171177 non-null  int64
 15  meanbp             171177 non-null  float64
 16  ph                 171177 non-null  float64
 17  hematocrit         171177 non-null  float64
 18  creatinine         171177 non-null  float64
 19  albumin            171177 non-null  float64
 20  pao2               171177 non-null  float64
 21  pco2               171177 non-null  float64
 22  bun                171177 non-null  float64
 23  glucose            171177 non-null  float64
 24  bilirubin          171177 non-null  float64
 25  fio2               171177 non-null  float64
dtypes: float64(16), int64(10)
memory usage: 34.0 MB

#第一部分数据提取

In [6]:
apacheApsVar_extract=apacheApsVar[['apacheapsvarid','patientunitstayid','urine','heartrate','wbc','temperature','sodium','creatinine','albumin','pco2','bun','bilirubin','fio2','ph','dialysis','sodium',"hematocrit",'glucose','respiratoryrate','vent']]
apacheApsVar_extract.to_csv("F:\\TrainTest\\EICU\\Data\\apacheApsVar_extract")

In [4]:
apachePatientResult=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\apachePatientResult.csv")
apachePatientResult

,apachepatientresultsid,patientunitstayid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,apacheversion,predictedicumortality,actualicumortality,predictediculos,...,predictedhospitallos,actualhospitallos,preopmi,preopcardiaccath,ptcawithin24h,unabridgedunitlos,unabridgedhosplos,actualventdays,predventdays,unabridgedactualventdays
0,26570,141168,critical care medicine (CCM),Unknown,49,65,IV,0.026988,EXPIRED,3.038388,...,7.546453,2.4972,0,0,0,2.4972,2.4972,NaN,NaN,NaN
1,26571,141168,critical care medicine (CCM),Unknown,49,65,IVa,0.028889,EXPIRED,3.091127,...,6.628720,2.4972,0,0,0,2.4972,2.4972,NaN,NaN,NaN
2,53135,141194,critical care medicine (CCM),Unknown,57,70,IV,0.037888,ALIVE,4.620982,...,13.338449,9.2167,0,0,0,3.3423,9.2167,NaN,NaN,NaN
3,53136,141194,critical care medicine (CCM),Unknown,57,70,IVa,0.046448,ALIVE,4.167129,...,12.978228,9.2167,0,0,0,3.3423,9.2167,NaN,NaN,NaN
4,8,141203,hospitalist,I,73,90,IVa,0.291609,ALIVE,8.670299,...,16.319389,3.7493,0,0,0,1.2979,3.7493,2.0,5.738093,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297059,3272802,3353251,cardiology,II,142,158,IVa,0.876797,ALIVE,8.920949,...,11.222566,13.4056,0,0,1,11.2909,13.4056,9.0,6.464630,9.0
297060,3262173,3353254,hospitalist,II,18,35,IV,0.008919,ALIVE,1.617038,...,5.995957,4.4549,0,0,0,0.2993,4.4549,NaN,NaN,NaN
297061,3262174,3353254,hospitalist,II,18,35,IVa,0.011004,ALIVE,2.045046,...,6.199350,4.4549,0,0,0,0.2993,4.4549,NaN,NaN,NaN
297062,3246241,3353263,nephrology,II,22,22,IVa,0.006508,ALIVE,1.754389,...,6.260686,6.7347,0,0,0,0.6444,6.7347,NaN,NaN,NaN
297063,3246240,3353263,nephrology,II,22,22,IV,0.005339,ALIVE,1.629617,...,6.098940,6.7347,0,0,0,0.6444,6.7347,NaN,NaN,NaN

#第二部分数据提取

In [11]:
apachePatientResult_extract=apachePatientResult[['patientunitstayid','apachescore','actualicumortality','actualhospitallos','unabridgedunitlos']]
apachePatientResult_extract.to_csv("F:\\TrainTest\\EICU\\Data\\apachePatientResult_extract")

In [13]:
carePlanCareProvider=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\carePlanCareProvider.csv")
carePlanCareProvider

,cplcareprovderid,patientunitstayid,careprovidersaveoffset,providertype,specialty,interventioncategory,managingphysician,activeupondischarge
0,1165205,141168,1844,NaN,critical care medicine (CCM),NaN,Managing,True
1,1165206,141168,74,NaN,cardiology,I,Managing,False
2,1165204,141168,1844,NaN,cardiology,I,Consulting,True
3,1111357,141178,4,NaN,internal medicine,I,Managing,True
4,1141236,141194,2775,NaN,critical care medicine (CCM),NaN,Managing,True
...,...,...,...,...,...,...,...,...
502760,10205335,3353254,15,NaN,NaN,II,Consulting,True
502761,10217608,3353263,206,NaN,hospitalist,II,Consulting,True
502762,10281811,3353263,101,NaN,hospitalist,II,Managing,False
502763,10217610,3353263,206,NaN,internal medicine,II,Consulting,True
502764,10217609,3353263,206,NaN,nephrology,II,Managing,True

In [14]:
carePlanEOL=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\carePlanEOL.csv")
carePlanEOL

,cpleolid,patientunitstayid,cpleolsaveoffset,cpleoldiscussionoffset,activeupondischarge
0,1179,242505,5196,0,True
1,1143,245984,1624,0,True
2,554,250634,92,-1079,True
3,726,251196,10049,8696,True
4,724,251924,4401,-921,True
...,...,...,...,...,...
1428,53472,3240722,3443,2153,True
1429,53738,3244177,1616,254,True
1430,53757,3246113,498,-934,True
1431,53824,3246280,1615,1708,True
1432,53812,3247135,3298,2040,True

In [15]:
carePlanGeneral=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\carePlanGeneral.csv")
carePlanGeneral

,cplgeneralid,patientunitstayid,activeupondischarge,cplitemoffset,cplgroup,cplitemvalue
0,4021595,141168,False,1846,Airway,Not intubated/normal airway
1,3519292,141168,True,1450,DVT Prophylaxis,Combined device and drug therapy
2,3997297,141168,True,2160,Ventilation,Ventilated - with daily extubation evaluation
3,3732045,141168,True,2244,Stress Ulcer Prophylaxis,Proton pump inhibitor
4,3522606,141168,False,74,Airway,Not intubated/normal airway
...,...,...,...,...,...,...
3115013,58850353,3353263,True,101,Activity,Ambulate
3115014,59276252,3353263,True,101,Analgesia,Parenteral - bolus prn
3115015,58840595,3353263,True,101,Sedation,None
3115016,59230366,3353263,True,101,Ventilation,Spontaneous - adequate
3115017,59154887,3353263,True,101,Airway,Not intubated/normal airway

In [16]:
carePlanGoal=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\carePlanGoal.csv")
carePlanGoal

,cplgoalid,patientunitstayid,cplgoaloffset,cplgoalcategory,cplgoalvalue,cplgoalstatus,activeupondischarge
0,91282,243061,74,Infection/Labs,Absence of fever,Active,True
1,91281,243061,74,Infection/Labs,Absence of sepsis,Active,True
2,64328,243698,35,Neurologic,Absence of seizures,Active,True
3,64327,243698,35,Neurologic,Neurologic status stable,Active,True
4,64329,243698,35,Neurologic,Neurologic status improving post neurologic event,Active,True
...,...,...,...,...,...,...,...
504134,10634241,3206731,38632,Nutrition/Skin,NaN,Active,False
504135,10634345,3210261,24586,Patient-Family,NaN,Active,True
504136,10634308,3211655,2815,Other,NaN,Active,True
504137,10634585,3212559,837,Nutrition/Skin,NaN,Active,True
504138,10733796,3327979,179,Patient-Family,NaN,Active,False

In [17]:
carePlanInfectiousDisease=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\carePlanInfectiousDisease.csv")
carePlanInfectiousDisease

,cplinfectid,patientunitstayid,activeupondischarge,cplinfectdiseaseoffset,infectdiseasesite,infectdiseaseassessment,responsetotherapy,treatment
0,911,242082,True,166,Urinary tract,Definite infection,NaN,NaN
1,3582,242154,True,7992,Lung,Definite infection,NaN,NaN
2,4053,242787,True,666,Lung,Definite infection,NaN,NaN
3,4923,242982,True,3353,Blood,Definite infection,NaN,NaN
4,3381,243208,False,743,Intra-abdominal,Definite infection,NaN,NaN
...,...,...,...,...,...,...,...,...
8051,128825,3238546,True,11401,Blood,Definite infection,NaN,NaN
8052,128848,3238807,True,7059,Prosthetic device,Definite infection,NaN,NaN
8053,129164,3240303,True,4584,Blood,Definite infection,NaN,NaN
8054,128742,3242665,True,856,Lung,Definite infection,NaN,NaN
8055,128947,3243236,True,9081,Blood,Definite infection,NaN,NaN

In [18]:
customLab=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\customLab.csv")
customLab

,customlabid,patientunitstayid,labotheroffset,labothertypeid,labothername,labotherresult,labothervaluetext
0,24655,242772,-71,1,CLO Test,NaN,POSITIVE
1,24656,242772,-99,1,GFR,NaN,>60
2,30840,242772,-99,3,Abs Neuts,3.50,3.5
3,30841,242772,-99,3,Neuts,66.00,66
4,25981,243249,1876,1,Ionized Calcium,4.39,4.39
...,...,...,...,...,...,...,...
1077,120265,3053382,2039,7,Peep High/ Peep Low,NaN,25/10
1078,120262,3053382,1728,7,Peep High/ Peep Low,NaN,30/10
1079,120263,3053382,1905,7,Peep High/ Peep Low,NaN,30/10
1080,120261,3053382,1414,7,Peep High/ Peep Low,NaN,25/5
1081,120264,3053382,1986,7,Peep High/ Peep Low,NaN,30/10

In [12]:
diagnosis=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\diagnosis.csv")
diagnosis

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority
0,4222318,141168,False,72,cardiovascular|chest pain / ASHD|coronary arte...,"414.00, I25.10",Other
1,3370568,141168,True,118,cardiovascular|ventricular disorders|cardiomyo...,NaN,Other
2,4160941,141168,False,72,pulmonary|disorders of the airways|COPD,"491.20, J44.9",Other
3,4103261,141168,True,118,pulmonary|disorders of the airways|COPD,"491.20, J44.9",Other
4,3545241,141168,True,118,cardiovascular|ventricular disorders|congestiv...,"428.0, I50.9",Other
...,...,...,...,...,...,...,...
2710667,46330138,3353251,False,11304,renal|disorder of urinary tract / renal system...,"599.0, N39.0",Other
2710668,46150971,3353251,False,4080,cardiovascular|shock / hypotension|sepsis,"038.9, A41.9",Major
2710669,46259796,3353254,True,41,renal|disorder of kidney|acute renal failure|d...,"584.9, N17.9",Major
2710670,46204273,3353254,True,41,gastrointestinal|GI bleeding / PUD|lower GI bl...,"578.9, K92.2",Primary
2710671,46335124,3353263,True,100,pulmonary|disorders of vasculature|pulmonary e...,"415.19, I26.99",Other

In [14]:
diagnosis_extract=diagnosis[['patientunitstayid','icd9code']]
diagnosis_extract.to_csv("F:\\TrainTest\\EICU\\Data\\diagnosis_extract")

In [21]:
hospital=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\hospital.csv")
hospital

     hospitalid numbedscategory teachingstatus   region
0            56            <100              f  Midwest
1            58       100 - 249              f  Midwest
2            59            <100              f  Midwest
3            60            <100              f  Midwest
4            61            <100              f  Midwest
..          ...             ...            ...      ...
203         447             NaN              f  Midwest
204         449          >= 500              t  Midwest
205         452             NaN              f  Midwest
206         458          >= 500              f    South
207         459       100 - 249              f    South

[208 rows x 4 columns]

In [23]:
infusionDrug=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\infusionDrug.csv")
infusionDrug

E:\Anaconda\envs\acative\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,infusiondrugid,patientunitstayid,infusionoffset,drugname,drugrate,infusionrate,drugamount,volumeoffluid,patientweight
0,1953469,242040,457,Milrinone (mcg/kg/min),.43,11.8,20.0,100.0,91.7
1,1998443,242082,425,Norepinephrine (mcg/min),10.93,41.0,4.0,250.0,NaN
2,1968206,242082,125,Norepinephrine (mcg/min),7,26.3,4.0,250.0,NaN
3,1991487,242082,665,NS (ml/hr),200,200.0,NaN,NaN,NaN
4,1969910,242082,55,Norepinephrine (mcg/min),2.13,8.0,4.0,250.0,NaN
...,...,...,...,...,...,...,...,...,...
4803714,75192643,3353251,2743,Insulin 250 Units Sodium Chloride 0.9% 250 ml ...,2.5,NaN,NaN,NaN,NaN
4803715,75244146,3353251,2683,Insulin 250 Units Sodium Chloride 0.9% 250 ml ...,2.2,NaN,NaN,NaN,NaN
4803716,75070892,3353251,1303,Norepinephrine MAX 32 mg Dextrose 5% 250 ml (m...,12,NaN,NaN,NaN,NaN
4803717,75161904,3353263,800,Heparin 25000 Units Dextrose 5% 500 ml Premix...,19,NaN,NaN,NaN,NaN
4803718,75177179,3353263,328,Heparin 25000 Units Dextrose 5% 500 ml Premix...,15,NaN,NaN,NaN,NaN

In [24]:
infusionDrug.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803719 entries, 0 to 4803718
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   infusiondrugid     int64
 1   patientunitstayid  int64
 2   infusionoffset     int64
 3   drugname           object
 4   drugrate           object
 5   infusionrate       float64
 6   drugamount         float64
 7   volumeoffluid      float64
 8   patientweight      float64
dtypes: float64(4), int64(3), object(2)
memory usage: 329.8+ MB

In [25]:
intakeOutput=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\intakeOutput.csv")
intakeOutput

MemoryError: Unable to allocate 551. MiB for an array with shape (6, 12030289) and data type float64

In [26]:
lab=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\lab.csv")
lab

MemoryError: Unable to allocate 512. KiB for an array with shape (65536,) and data type int64

In [27]:
medication=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\medication.csv")
medication

E:\Anaconda\envs\acative\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,medicationid,patientunitstayid,drugorderoffset,drugstartoffset,drugivadmixture,drugordercancelled,drugname,drughiclseqno,dosage,routeadmin,frequency,loadingdose,prn,drugstopoffset,gtc
0,7426715,141168,309,666,No,No,METOPROLOL TARTRATE 25 MG PO TABS,2102.0,25 3,PO,Q12H SCH,NaN,No,1826,0
1,9643232,141168,1847,1832,No,No,3 ML - IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/...,NaN,3 1,NEBULIZATION,Q4H Resp PRN,NaN,Yes,2047,0
2,10270090,141168,296,1386,No,No,ASPIRIN EC 81 MG PO TBEC,1820.0,81 3,PO,Daily,NaN,No,2390,0
3,9496768,141168,2048,2029,No,No,3 ML - IPRATROPIUM-ALBUTEROL 0.5-2.5 (3) MG/...,NaN,3 1,NEBULIZATION,Q4H Resp PRN,NaN,Yes,2390,0
4,11259680,141168,117,246,No,No,ENOXAPARIN SODIUM 40 MG/0.4ML SC SOLN,NaN,40 3,SC,Daily,NaN,No,1721,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7301848,110813954,3353263,6556,6535,No,Yes,OXYCODONE/APAP 5MG/325MG,1741.0,1 TAB,ORAL,Q4HRSPRN,NaN,Yes,0,2
7301849,111092277,3353263,526,527,No,No,HYDROMORPHONE HCL,34805.0,2 MG,INTRAVEN,NaN,NaN,No,527,2
7301850,111363990,3353263,63,58,No,Yes,DOCUSATE SODIUM,1326.0,100 MG,ORAL,DAILY,NaN,No,0,65
7301851,111843126,3353263,569,1250,No,Yes,DOCUSATE SODIUM,1326.0,100 MG,ORAL/TUBE,QHS,NaN,No,0,65
7301852,110892948,3353263,570,557,No,No,NaN,22708.0,250 ML,INTRAVEN,DRIP,NaN,No,6538,2

In [28]:
microLab=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\microLab.csv")
microLab

,microlabid,patientunitstayid,culturetakenoffset,culturesite,organism,antibiotic,sensitivitylevel
0,549559,983524,-688,"Blood, Venipuncture",gram positive rods,NaN,NaN
1,549555,983524,-5481,Stool,no growth,NaN,NaN
2,549565,983524,324,Stool,no growth,NaN,NaN
3,549562,983524,-686,"Blood, Central Line",gram negative rods,NaN,NaN
4,549564,983524,-681,"Blood, Central Line",gram positive cocci,NaN,NaN
...,...,...,...,...,...,...,...
16991,1617032,3160582,411,Other,mixed flora,NaN,NaN
16992,1617031,3160582,-521,"Blood, Venipuncture",no growth,NaN,NaN
16993,1617033,3160582,411,Other,Candida albicans,NaN,NaN
16994,1617030,3160582,-522,"Blood, Venipuncture",no growth,NaN,NaN
16995,1627296,3160583,-7,"Sputum, Tracheal Specimen",no growth,NaN,NaN

In [30]:
note=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\note.csv")
note

,noteid,patientunitstayid,noteoffset,noteenteredoffset,notetype,notepath,notevalue,notetext
0,3586546,176895,9,16,Comprehensive Progress,notes/Progress Notes/Assessment and Plan/View ...,Problem View,Problem View
1,3586547,176895,9,16,Comprehensive Progress,notes/Shared/View and Save/Save Options/Print/...,Copies,1
2,3586644,149700,0,1,Comprehensive Progress,notes/Progress Notes/Assessment and Plan/View ...,System View,SystemView
3,3586645,149700,0,1,Comprehensive Progress,notes/Shared/View and Save/Save Options/Print/...,Copies,1
4,3586662,208303,432,438,Comprehensive Progress,notes/Progress Notes/Admission Page One/Enter ...,Yes,Yes
...,...,...,...,...,...,...,...,...
2254174,92063776,3334513,9,19,Admission,notes/Progress Notes/Allergies / Preadmission ...,No,No
2254175,92063777,3334513,9,19,Admission,notes/Progress Notes/Allergies / Preadmission ...,Unknown,Unknown
2254176,92063781,3334513,9,19,Admission,notes/Progress Notes/Assessment and Plan/View ...,System View,SystemView
2254177,92063782,3334513,9,19,Admission,notes/Progress Notes/Assessment and Plan/Inclu...,Include Rx,Include Rx
2254178,92063783,3334513,9,19,Admission,notes/Shared/View and Save/Save Options/Print/...,Copies,1

In [2]:
nurseAssessment=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\nurseAssessment.csv")
nurseAssessment

,nurseassessid,patientunitstayid,nurseassessoffset,nurseassessentryoffset,cellattributepath,celllabel,cellattribute,cellattributevalue
0,23513188,356285,52,55,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Pupils,Pupils,"pupils equal, react to light"
1,27015042,356285,52,55,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Reflexes,Reflexes,normal
2,27033363,356285,52,55,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Motor Strength,Motor Strength,normal
3,31304644,356285,52,55,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Neurologic,LOC,normal
4,31304645,356285,52,55,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Neurologic,Orientation,to person
...,...,...,...,...,...,...,...,...
15602493,581673557,3157705,2238,2455,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Pacemaker/AICD,Pacemaker/AICD,NaN
15602494,581673565,3160563,978,1028,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Motor Strength,RUE,+2-No gravity
15602495,581673566,3160563,978,1028,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Motor Strength,RLE,+2-No gravity
15602496,581673567,3160563,978,1028,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Motor Strength,LUE,+4-Resists
15602497,581673568,3160563,978,1028,flowsheet|Flowsheet Cell Labels|Nursing Assess...,Motor Strength,LLE,+2-No gravity

In [3]:
nurseCare=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\nurseCare.csv")
nurseCare

,nursecareid,patientunitstayid,celllabel,nursecareoffset,nursecareentryoffset,cellattributepath,cellattribute,cellattributevalue
0,20961343,988422,Nutrition,4726,4790,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,enteral
1,20961390,1019315,Equipment,14479,14480,flowsheet|Flowsheet Cell Labels|Nursing Care|E...,Equipment,heels floated
2,20961391,1019315,Equipment,14479,14480,flowsheet|Flowsheet Cell Labels|Nursing Care|E...,Equipment,sling
3,20961392,1019315,Equipment,14479,14480,flowsheet|Flowsheet Cell Labels|Nursing Care|E...,Equipment,therapeutic bed
4,20961417,1047339,Nutrition,2971,2974,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,NPO
...,...,...,...,...,...,...,...,...
8311127,382497574,3141623,Nutrition,975,1238,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,NPO
8311128,382497684,3141044,Nutrition,996,1076,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,low sodium diet
8311129,382497685,3141044,Nutrition,996,1076,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,renal diet
8311130,382497714,3148763,Nutrition,3907,4280,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,diabetic diet
8311131,382497715,3148763,Nutrition,3907,4280,flowsheet|Flowsheet Cell Labels|Nursing Care|N...,Nutrition,renal diet

In [4]:
nurseCharting=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\nurseCharting.csv")

MemoryError: Unable to allocate 512. KiB for an array with shape (65536,) and data type int64

In [5]:
pastHistory=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\pastHistory.csv")
pastHistory

,pasthistoryid,patientunitstayid,pasthistoryoffset,pasthistoryenteredoffset,pasthistorynotetype,pasthistorypath,pasthistoryvalue,pasthistoryvaluetext
0,1141827,141168,60,72,Comprehensive Progress,notes/Progress Notes/Past History/Organ System...,AS,AS
1,1234145,141168,114,118,Comprehensive Progress,notes/Progress Notes/Past History/Organ System...,renal failure- not currently dialyzed,renal failure- not currently dialyzed
2,1141831,141168,60,72,Comprehensive Progress,notes/Progress Notes/Past History/Organ System...,CHF - class II,CHF - class II
3,1234141,141168,114,118,Comprehensive Progress,notes/Progress Notes/Past History/Past History...,Performed,Performed
4,1141830,141168,60,72,Comprehensive Progress,notes/Progress Notes/Past History/Organ System...,hypertension requiring treatment,hypertension requiring treatment
...,...,...,...,...,...,...,...,...
1149175,22269162,3353251,78,108,Admission,notes/Progress Notes/Past History/Organ System...,CABG - date unknown,CABG - date unknown
1149176,22236718,3353254,31,41,Admission,notes/Progress Notes/Past History/Past History...,Performed,Performed
1149177,22236719,3353254,31,41,Admission,notes/Progress Notes/Past History/Organ System...,COPD - moderate,COPD - moderate
1149178,22236720,3353254,31,41,Admission,notes/Progress Notes/Past History/Organ System...,atrial fibrillation - chronic,atrial fibrillation - chronic
1149179,22297135,3353263,96,100,Admission,notes/Progress Notes/Past History/Past History...,Performed,Performed

In [6]:
patient=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\patient.csv")
patient

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
0,141168,128919,Female,70,Caucasian,59,91,"Rhythm disturbance (atrial, supraventricular)",152.4,15:54:00,...,Direct Admit,1,admit,84.3,85.8,03:50:00,3596,Death,Expired,002-34851
1,141178,128927,Female,52,Caucasian,60,83,NaN,162.6,08:56:00,...,Emergency Department,1,admit,54.4,54.4,09:18:00,8,Step-Down Unit (SDU),Alive,002-33870
2,141179,128927,Female,52,Caucasian,60,83,NaN,162.6,08:56:00,...,ICU to SDU,2,stepdown/other,NaN,60.4,19:20:00,2042,Home,Alive,002-33870
3,141194,128941,Male,68,Caucasian,73,92,"Sepsis, renal/UTI (including bladder)",180.3,18:18:40,...,Floor,1,admit,73.9,76.7,15:31:00,4813,Floor,Alive,002-5276
4,141196,128943,Male,71,Caucasian,67,109,NaN,162.6,20:21:00,...,ICU to SDU,2,stepdown/other,NaN,63.2,22:23:00,1463,Floor,Alive,002-37665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200854,3353235,2743084,Male,50,Caucasian,458,1109,"CHF, congestive heart failure",175.3,04:55:00,...,Emergency Department,1,admit,90.0,99.2,23:18:00,1069,Telemetry,Alive,035-16382
200855,3353237,2743086,Female,79,Caucasian,458,1106,"Embolus, pulmonary",162.6,01:45:00,...,Direct Admit,1,admit,78.4,81.4,23:08:00,1269,Step-Down Unit (SDU),Alive,035-751
200856,3353251,2743099,Male,73,African American,458,1104,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,...,Emergency Department,1,admit,102.0,96.2,23:16:00,16259,Telemetry,Alive,035-5166
200857,3353254,2743102,Male,81,Caucasian,459,1108,"Bleeding, lower GI",185.4,07:43:00,...,Emergency Department,1,admit,83.9,92.9,19:25:00,431,Step-Down Unit (SDU),Alive,035-19511
200858,3353263,2743110,Male,35,African American,458,1106,"Embolus, pulmonary",182.9,03:22:00,...,Emergency Department,1,admit,100.8,100.8,20:38:00,928,Telemetry,Alive,035-22638

#第二次数据提取

In [8]:
patient_extract=patient[['patientunitstayid','gender','age','ethnicity']]
patient_extract

        patientunitstayid  gender age         ethnicity
0                  141168  Female  70         Caucasian
1                  141178  Female  52         Caucasian
2                  141179  Female  52         Caucasian
3                  141194    Male  68         Caucasian
4                  141196    Male  71         Caucasian
...                   ...     ...  ..               ...
200854            3353235    Male  50         Caucasian
200855            3353237  Female  79         Caucasian
200856            3353251    Male  73  African American
200857            3353254    Male  81         Caucasian
200858            3353263    Male  35  African American

[200859 rows x 4 columns]

In [9]:
physicalExam=pd.read_csv("F:\TrainTest\EICU\Eicu_Data\physicalExam.csv")
physicalExam

,physicalexamid,patientunitstayid,physicalexamoffset,physicalexampath,physicalexamvalue,physicalexamtext
0,5253099,176895,9,notes/Progress Notes/Physical Exam/Physical Ex...,scored,scored
1,5253100,176895,9,notes/Progress Notes/Physical Exam/Physical Ex...,Performed - Structured,Performed - Structured
2,5253104,176895,9,notes/Progress Notes/Physical Exam/Physical Ex...,Current,68.3
3,5253105,176895,9,notes/Progress Notes/Physical Exam/Physical Ex...,Intake Total,2725
4,5253106,176895,9,notes/Progress Notes/Physical Exam/Physical Ex...,Output Total,1360
...,...,...,...,...,...,...
9212311,161973408,3350517,28,notes/Progress Notes/Physical Exam/Physical Ex...,Total Net,-400
9212312,161973409,3350517,28,notes/Progress Notes/Physical Exam/Physical Ex...,6,6
9212313,161973410,3350517,28,notes/Progress Notes/Physical Exam/Physical Ex...,5,5
9212314,161973411,3350517,28,notes/Progress Notes/Physical Exam/Physical Ex...,4,4
9212315,161973537,3334513,9,notes/Progress Notes/Physical Exam/Physical Ex...,Not Performed,Not Performed

In [11]:
respiratoryCare=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\respiratoryCare.csv")
respiratoryCare

E:\Anaconda\envs\acative\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (4,5,6,12,26,27,28,30,31,32,33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,respcareid,patientunitstayid,respcarestatusoffset,currenthistoryseqnum,airwaytype,airwaysize,airwayposition,cuffpressure,ventstartoffset,ventendoffset,...,peeplimit,cpaplimit,setapneainterval,setapneatv,setapneaippeephigh,setapnearr,setapneapeakflow,setapneainsptime,setapneaie,setapneafio2
0,555232,141168,1926,1,NaN,NaN,NaN,NaN,1566,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,550536,141227,1567,1,NaN,NaN,NaN,NaN,1267,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,558282,141233,1618,2,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,558281,141233,5,1,NaN,NaN,NaN,NaN,-298,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,559466,141276,228,2,NaN,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865376,6515203,3353263,3722,4,No Artificial Airway,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
865377,6515204,3353263,4306,5,No Artificial Airway,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
865378,6514773,3353263,432,2,No Artificial Airway,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
865379,6514772,3353263,14,1,No Artificial Airway,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
865380,6514774,3353263,3320,3,No Artificial Airway,NaN,NaN,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
respiratoryCharting=pd.read_csv("F:\\TrainTest\\EICU\Eicu_Data\\respiratoryCharting.csv")
respiratoryCharting

E:\Anaconda\envs\acative\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,respchartid,patientunitstayid,respchartoffset,respchartentryoffset,respcharttypecat,respchartvaluelabel,respchartvalue
0,3,221468,4679,4679,respFlowCareData,RT Vent On/Off,Continued
1,4,221468,4679,4679,respFlowSettings,FiO2,40
2,5,221468,4679,4679,respFlowSettings,Vent Rate,14
3,6,221468,4679,4679,respFlowSettings,Tidal Volume (set),450
4,7,221468,4679,4679,respFlowSettings,TV/kg IBW,5.4720
...,...,...,...,...,...,...,...
20168171,255567518,3335097,15149,15149,respFlowPtVentData,Peak Insp. Pressure,14
20168172,255567519,3335097,15149,15149,respFlowPtVentData,Exhaled MV,7.9
20168173,255567520,3335097,15149,15149,respFlowPtVentData,Mean Airway Pressure,6
20168174,255567527,3331083,126,126,respFlowSettings,FiO2,40
20168175,255567530,3344105,56602,56602,respFlowSettings,FiO2,40

In [14]:
treatment=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\treatment.csv")
treatment

,treatmentid,patientunitstayid,treatmentoffset,treatmentstring,activeupondischarge
0,8399138,242040,198,cardiovascular|hypertension|angiotensin II rec...,False
1,8626134,242040,198,cardiovascular|myocardial ischemia / infarctio...,False
2,8517569,242040,198,infectious diseases|medications|therapeutic an...,False
3,9597686,242040,616,cardiovascular|non-operative procedures|diagno...,False
4,9334096,242040,618,infectious diseases|medications|therapeutic an...,True
...,...,...,...,...,...
3688740,82519717,3353251,291,pulmonary|radiologic procedures / bronchoscopy...,False
3688741,82608952,3353251,291,pulmonary|ventilation and oxygenation|mechanic...,False
3688742,82541591,3353254,41,cardiovascular|intravenous fluid|normal saline...,True
3688743,82230708,3353254,41,cardiovascular|intravenous fluid|blood product...,True
3688744,82479989,3353263,100,pulmonary|medications|anticoagulant administra...,True

In [23]:
vitalAperiodic=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\vitalAperiodic.csv")
vitalAperiodic

MemoryError: Unable to allocate 1.87 GiB for an array with shape (10, 25075074) and data type float64

In [26]:
pd.read_csv('"F:\\TrainTest\\EICU\\Eicu_Data\\vitalAperiodic.csv"', delim_whitespace=True, usecols=["patientunitstayid", "respiration"])

OSError: [Errno 22] Invalid argument: '"F:\\TrainTest\\EICU\\Eicu_Data\\vitalAperiodic.csv"'

In [22]:
#for chunk in pd.read_csv('F:\\TrainTest\\EICU\\Eicu_Data\\vitalAperiodic.csv',chunksize=1000):
  #  process(chunk)

NameError: name 'process' is not defined

In [27]:
vitalPeriodic=pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\vitalPeriodic.csv")
vitalPeriodic

MemoryError: Unable to allocate 256. KiB for an array with shape (32768,) and data type float64

In [ ]:
mylist = []
for chunk in pd.read_csv("F:\\TrainTest\\EICU\\Eicu_Data\\vitalPeriodic.csv", chunksize=1000):
    mylist.append(chunk)
    temp_df = pd.concat(mylist, axis= 0)

In [31]:
patient_extract.to_csv("F:\TrainTest\EICU\Data\patient_extract")

In [32]:
apacheApsVar_extract.to_csv("F:\\TrainTest\\EICU\Data\\apacheApsVar_extract")

In [3]:
eicu=pd.read_csv("early_24hr_eicu.csv")
eicu

,PatientStayID,Class,unitdischargeoffset_x,apachescore,gender,age,ethnicity,hospitalid,apacheadmissiondx,admissionheight,...,admissionweight,numbedscategory,teachingstatus,region,unitdischargeoffset_y,24hr_AKI,unitdischargeoffset_x.1,first_24hr_dialysis,unitdischargeoffset_y.1,first_24hr_surgical
0,242154,1,8792,77.0,Female,46.0,Caucasian,79,"Sepsis, pulmonary",157.48,...,53.09,4.0,0,2.0,8792,False,8792,0,8792,0
1,242290,0,1656,77.0,Female,75.0,Other/Unknown,79,"Sepsis, unknown",165.10,...,73.30,4.0,0,2.0,1656,True,1656,0,1656,0
2,242474,0,1494,64.0,Male,52.0,Native American,79,Drug withdrawal,177.80,...,94.00,4.0,0,2.0,1494,False,1494,0,1494,0
3,242505,1,6920,78.0,Female,90.0,Caucasian,79,"Sepsis, cutaneous/soft tissue",165.10,...,61.80,4.0,0,2.0,6920,False,6920,0,6920,0
4,242714,0,2985,-1.0,Male,78.0,Caucasian,79,"Hematoma, subdural",182.90,...,89.20,4.0,0,2.0,2985,False,2985,0,2985,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18300,3352193,0,1955,-1.0,Female,19.0,Other/Unknown,458,Head/face trauma,157.50,...,50.00,4.0,0,4.0,1955,False,1955,0,1955,0
18301,3352331,0,2204,48.0,Female,75.0,Caucasian,459,"CVA, cerebrovascular accident/stroke",167.60,...,97.52,2.0,0,4.0,2204,False,2204,0,2204,0
18302,3352964,0,2466,75.0,Female,85.0,Caucasian,459,"CHF, congestive heart failure",162.00,...,86.40,2.0,0,4.0,2466,False,2466,0,2466,0
18303,3353044,0,4788,41.0,Male,52.0,Caucasian,459,Drug withdrawal,175.00,...,52.00,2.0,0,4.0,4788,False,4788,0,4788,0
18304,3353077,0,6050,36.0,Female,60.0,African American,458,"Neoplasm, neurologic",165.10,...,120.60,4.0,0,4.0,6050,False,6050,0,6050,1

In [4]:
early_24hr_validation_data_set=pd.read_csv("F:\TrainTest\EICU\Data_deal\early_24hr_validation_data_set.csv")
early_24hr_validation_data_set

E:\Anaconda\envs\acative\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (37,45,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,PatientStayID,Class,unitdischargeoffset,apachescore,gender,age,ethnicity,hospitalid,apacheadmissiondx,admissionheight,...,sofa_cardio,sofa_liver,sofa_coag,sofa_kidney,sofa_score,qsofa_altered_mental,qsofa_resp_rate,qsofa_sys_bp,qsofa_score,first_24hr_urine
0,242154,1,8792,77.0,Female,46.0,Caucasian,79,"Sepsis, pulmonary",157.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,242290,0,1656,77.0,Female,75.0,Other/Unknown,79,"Sepsis, unknown",165.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,242474,0,1494,64.0,Male,52.0,Native American,79,Drug withdrawal,177.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,242505,1,6920,78.0,Female,90.0,Caucasian,79,"Sepsis, cutaneous/soft tissue",165.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,242714,0,2985,-1.0,Male,78.0,Caucasian,79,"Hematoma, subdural",182.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18300,3352193,0,1955,-1.0,Female,19.0,Other/Unknown,458,Head/face trauma,157.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18301,3352331,0,2204,48.0,Female,75.0,Caucasian,459,"CVA, cerebrovascular accident/stroke",167.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18302,3352964,0,2466,75.0,Female,85.0,Caucasian,459,"CHF, congestive heart failure",162.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18303,3353044,0,4788,41.0,Male,52.0,Caucasian,459,Drug withdrawal,175.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18304,3353077,0,6050,36.0,Female,60.0,African American,458,"Neoplasm, neurologic",165.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN